### ISSUE TITLE
我有个小小的请求

### ISSUE THREAD

**Issue by XmJwit** [f1tz/BlockWin10AU#1]
您的知乎里有这样的评论
win10为什么不能选择关掉自动更新？ - 鲍抱抱的回答 - 知乎
https://www.zhihu.com/question/46365518/answer/353417894

东南偏南29 天前
这个办法可逆吗？因为平时会玩地平线3..商店的游戏需要开启update

鲍抱抱 (作者) 回复东南偏南8 天前
可以的，根据批处理做的操作来做逆向操作

所以我来求求大神您弄个可逆的bat，感激不尽（快哭啦）

**Comment by f1tz** [comment]
@XmJwit 没有在使用Windows商店，不过应该只需要开启Windows Update服务吧？

- 试着在”服务“启动它，运行里输入“services.msc”，找到”Windows Update“并启动

**Comment by Albertwindows** [comment]
@f1tz 请问为什么感觉在执行了您的.bat文件之后,内存占用量从原来的40%到了80%呢?是不是有什么没考虑到的呢?
